version: "3"

services:
  # Dremio
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
      - 45678:45678
    container_name: dremio
    volumes:
      - ./dremio_volume/conf:/opt/dremio/conf
      - ./dremio_volume/shared_mount_path:/shared_mount_path
    networks:
      - demo

  # Data Loader
  data_loader:
    build:
      context: ./data_loader_script
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - demo

  # MySQL
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql_database
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=movies
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_volume:/var/lib/mysql
    networks:
      - demo

  # Spark Notebook
  spark-notebook:
    image: jupyter/pyspark-notebook
    command: start-notebook.sh --ServerApp.password='sha1:d2887803f259:31c1bd6d04cd68c3317e88081a6b2a89a8f7f30b'
    ports:
      - 8888:8888
      - 4040:4040
    depends_on:
      - dremio
    volumes:
      - ./spark-notebooks:/home/jovyan/work
    networks:
      - demo

networks:
  demo:
